# Training settings
base_dir: data/characters  # Base directory for character data

# Output
output_dir: models/lora_weights

# Model settings
sdxl_model_path: checkpoints/sdxl_base
controlnet_model_path: checkpoints/controlnet_pretrained

# LoRA config
lora_rank: 8

# Training hyperparams
resolution: 1024
batch_size: 4
gradient_accumulation_steps: 2
mixed_precision: bf16
learning_rate: 1e-4
max_train_steps: 5000
