# Training settings
base_dir: data/characters  # Base directory for character data

# Output
output_dir: models/lora_weights

# Model settings
sdxl_model_path: stabilityai/stable-diffusion-xl-base-1.0

resolution: 512 
controlnet_resolution: 512

training:
  resolution: 512 
  num_epochs: 200
  max_train_steps: 10000
  batch_size: 2
  gradient_accumulation_steps: 4
  learning_rate: 0.0001
  warmup_ratio: 0.001
  patience: 25
  save_steps: 500
  preview_steps: 50
  log_steps: 10
  
model:
  lora_rank: 4
  lora_alpha: 32
  lora_dropout: 0.1
  lambda_identity: 0.25
  lighting_dim: 16
  hidden_dim: 512
  output_dim: 2048 
  ema_decay: 0.9999
  bias: none
  task_type: UNET
  target_modules:
    - to_q
    - to_k
    - to_v
    - to_out.0
    - ff.net.0.proj
    - ff.net.2

controlnet:
  input_channels: 3
  conditioning: normal_map
  resolution: 512

optimization:
  mixed_precision: "bf16"
  use_8bit_adam: true
  gradient_checkpointing: true
  enable_xformers: true

debug:
  enabled: true  # Set to true to enable detailed debugging output